name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: Run build
      run: lein uberjar
    - name: copy build standalone jar
      run: mkdir dist/ && cp target/uberjar/*standalone.jar dist
    - name: Deploy to Server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.SSH_KEY }}
        ARGS: "-e -c -r --delete"
        SERVER_PORT: ${{ secrets.REMOTE_PORT }}
        FOLDER: "dist/"
        SERVER_IP: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        SERVER_DESTINATION: ${{ secrets.TARGET}}
